spring.application.name=KAPPA-Orders-BackEnd

spring.data.mongodb.uri=mongodb+srv://manuelguarnizog_db_user:slmEouXGl5LaTDbg@clustereciexpress.m7ljcsf.mongodb.net/?appName=ClusterECIEXPRESS
spring.data.mongodb.database = orders-db


gateway.url=http://gateway:8081/api


server.port=8086